### ISSUE TITLE
Publish to python's pip

### ISSUE THREAD

**Issue by rjcoelho** [azadkuh/cmus-osx#17]
This way I can pip3 install cmus-osx. See http://peterdowns.com/posts/first-time-with-pypi.html

**Comment by PhilipTrauner** [comment]
Thanks for the suggestion, but it was a conscious decision to write a custom installation script instead of publishing cmus-osx on PyPI. As far as I know there is no easy way to define a custom installation directory when using setuptools. This could be circumvented by writing a CLI script which would then install cmus-osx, but currently I really don't want to go through that trouble.
