### ISSUE TITLE
Is there any way to get rid of the rocket icon?

### ISSUE THREAD

**Issue by EmmaSimon** [azadkuh/cmus-osx#18]
I assume it's coming from `pyobjc`, I can't find any options about it anywhere (in your config, appkit, or pyobjc). It's not a huge deal, it's mostly just sort of annoying.

**Comment by PhilipTrauner** [comment]
Yep, the rocket is the app icon of `Python.app` (`/usr/local/opt/python3/Frameworks/Python.framework/Versions/3.6/Resources/Python.app`) which is part of `Python.framework`. Through some experimentation I've been able to conclude that Notification Center only really cares about app identifiers (`org.python.python` in this case) and so changing the app icon of `Python.app` should theoretically be a viable approach to get rid of the rocket. I say theoretical because my Mac is currently stuck in a bootloop, and I've not been able to test this assumption. What I have been able to conclude is the fact that app icons are cached pretty heavily, so one would also have to find a way to invalidate the Notification Center icon cache.

Anyway, expect a more concrete reply once I get my Mac up and running again. :sweat_smile:

**Comment by EmmaSimon** [comment]
Thanks! I'll try to look into a bit in the next few days.

**Comment by PhilipTrauner** [comment]
Update on my icon replacement theory: It doesn't work. 😢 
Even after clearing every possible icon cache that macOS maintains, the rocket is still alive. I have no clue where the icon could possibly be originating from as I've replaced every single occurence of it.

Still, if you manage to get rid of the rocket I'd be glad to accept a pull request or generally know how you did it. 😄

**Comment by EmmaSimon** [comment]
So I updated `Info.plist` in `Python.app` to point to a different icon file, which I got from googling "blank icns file", and blank apparently means without data, cuz it just shows a default flower icon thing. It only started showing up after I cleared some of the caches then restarted. Just a restart might work. I tried downloading a "transparent" icon file, and we'll see if that makes something else show up, but I've been too lazy to restart since then.

**Comment by EmmaSimon** [comment]
Oh, heh, I'm just dumb and got a blank *file* icon from textmate I guess and never bothered previewing it. It is showing up though.

 https://github.com/textmate/document-icons/blob/master/Blank.icns

**Comment by PhilipTrauner** [comment]
Didn't know that overriding the icon from within the `.plist` file works :sweat_smile:. 
I'll close this issue for now, as globally overriding the icon doesn't really seem like the right solution in my opinion, especially with all the cache clearing uncertainty going on. 
Still, thanks for letting me know how you managed to replace the icon :+1:
