### ISSUE TITLE
Cannot change iTunes permissions

### ISSUE THREAD

**Issue by jiqbal48** [azadkuh/cmus-osx#19]
Hi, 
I recently upgraded my Mac to use Mojave and cmus-osx didn't seem to be working, so I uninstalled and reinstalled it. However I get the following error msg: 

```
╰─$ sudo ./setup.py install
Password:
cmus config directory: '/Users/jiqbal/.config/cmus/'
Disabling iTunes. Uninstall to re-enable!
chmod: Unable to change file mode on /Applications/iTunes.app/Contents/MacOS/iTunes: Operation not permitted
Installed. To enable notifications execute
set status_display_program=/Users/jiqbal/.config/cmus/cmus-osx/notify.py
in cmus.
```
I did some googling, but couldn't find any solution for this. The `next` and `previous` media keys work fine, but pressing `pause|play` opens up itunes. 

Oh, forgot to add, I have looked at https://github.com/PhilipTrauner/cmus-osx/issues/11 and added 
`export PYTHON_CONFIGURE_OPTS="--enable-framework"`
to my .zshrc
Also am using `pyenv 1.2.8` and `Python 3.6.5`

**Comment by PhilipTrauner** [comment]
Damn, I knew this trick would stop working at some point 😞 
Please use something like [noTunes](https://github.com/tombonez/noTunes) until I figure out a better way to prevent iTunes from launching. 😬

**Comment by dmlemos** [comment]
What works for me is every time the OS gets upgraded I must boot into recovery mode to disable iTunes manually.

Once in recovery mode, mount the system volume and then execute:
`cd /Volume/MacOS` (where MacOS is the name of your volume)
`chmod -x /Applications/iTunes.app/Contents/MacOS/iTunes`

I have been doing this for quite some time actually.
The `setup.py` never complains because the chmod is already done so it won't throw an error 😃
