### ISSUE TITLE
HOME variable is expanding again

### ISSUE THREAD

**Issue by dmlemos** [azadkuh/cmus-osx#28]
Since the last release, home variable is expanding again, both in the `rc` and `autosave` files, as well as the scripts.

I would honestly prefer to not have hard-coded paths to maintain portability of the configuration.

Is it possible to revert back to call the python scripts directly in the cmus config files? ala `shell ~/.cmus/cmus-osx/media-keys.py &`

I don't mind doing a PR for this. Already made some changes to it.

**Comment by PhilipTrauner** [comment]
> Is it possible to revert back to call the python scripts directly in the cmus config files? ala shell ~/.cmus/cmus-osx/media-keys.py &

I made this change to address two shortcomings:
1. The system Python environment was always assumed
2. Switching between development and normal usage was cumbersome

I won't be undoing that change, but I would accept a PR that makes the installer write out paths relative to the user's home directory instead of the absolute path in the automatically generated `.sh` scripts as well as the config file.

**Comment by dmlemos** [comment]
That's a very valid explanation.

I've opened a PR for this.
